/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./../src/components/menu/asideMenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileUploadMoreChunk: typeof import('./../src/components/fileUpload/fileUploadMoreChunk.vue')['default']
    FileUploadMoreChunkConcur: typeof import('./../src/components/fileUpload/fileUploadMoreChunkConcur.vue')['default']
    FileUploadMoreFull: typeof import('./../src/components/fileUpload/fileUploadMoreFull.vue')['default']
    FileUploadMoreFullConcur: typeof import('./../src/components/fileUpload/fileUploadMoreFullConcur.vue')['default']
    FileUploadOneChunk: typeof import('./../src/components/fileUpload/fileUploadOneChunk.vue')['default']
    FileUploadOneChunkConcur: typeof import('./../src/components/fileUpload/fileUploadOneChunkConcur.vue')['default']
    FileUploadOneFull: typeof import('./../src/components/fileUpload/fileUploadOneFull.vue')['default']
    IconSelect: typeof import('./../src/components/iconSelect/iconSelect.vue')['default']
    ImageCrop: typeof import('./../src/components/imageCrop/imageCrop.vue')['default']
    Pagination: typeof import('./../src/components/pagination/pagination.vue')['default']
    RightClickMenu: typeof import('./../src/components/rightClickMenu/rightClickMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svgIcon/svgIcon.vue')['default']
    TablePage: typeof import('./../src/components/tablePage/tablePage.vue')['default']
    TablePageFullFeatured: typeof import('./../src/components/tablePage/tablePageFullFeatured.vue')['default']
    Tooltip: typeof import('./../src/components/tooltip/tooltip.vue')['default']
  }
}
