/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./../src/components/menu/asideMenu.vue')['default']
    FileUploadMoreChunk: typeof import('./../src/components/fileUpload/fileUploadMoreChunk.vue')['default']
    FileUploadMoreChunkConcur: typeof import('./../src/components/fileUpload/fileUploadMoreChunkConcur.vue')['default']
    FileUploadMoreFull: typeof import('./../src/components/fileUpload/fileUploadMoreFull.vue')['default']
    FileUploadMoreFullConcur: typeof import('./../src/components/fileUpload/fileUploadMoreFullConcur.vue')['default']
    FileUploadOneChunk: typeof import('./../src/components/fileUpload/fileUploadOneChunk.vue')['default']
    FileUploadOneChunkConcur: typeof import('./../src/components/fileUpload/fileUploadOneChunkConcur.vue')['default']
    FileUploadOneFull: typeof import('./../src/components/fileUpload/fileUploadOneFull.vue')['default']
    IconSelect: typeof import('./../src/components/iconSelect/iconSelect.vue')['default']
    ImageCrop: typeof import('./../src/components/imageCrop/imageCrop.vue')['default']
    Pagination: typeof import('./../src/components/pagination/pagination.vue')['default']
    RightClickMenu: typeof import('./../src/components/rightClickMenu/rightClickMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svgIcon/svgIcon.vue')['default']
    Tooltip: typeof import('./../src/components/tooltip/tooltip.vue')['default']
  }
}
